"use client";

import { useState } from "react";
import { useCopilotAction } from "@copilotkit/react-core";

interface A2UIComponent {
  type: string;
  props?: Record<string, any>;
  children?: A2UIComponent[];
}

interface A2UISpec {
  version: string;
  components: A2UIComponent[];
  metadata?: {
    title?: string;
    description?: string;
    author?: string;
  };
}

export default function A2UIComposer() {
  const [spec, setSpec] = useState<A2UISpec>({
    version: "1.0",
    components: [],
    metadata: {
      title: "My A2UI Composition",
      description: "Generated by A2UI Composer"
    }
  });
  const [selectedComponent, setSelectedComponent] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [previewMode, setPreviewMode] = useState(false);

  // A2UI component templates
  const componentTemplates = {
    button: {
      type: "button",
      props: {
        label: "Click me",
        variant: "primary",
        size: "medium"
      }
    },
    text: {
      type: "text",
      props: {
        content: "Hello, World!",
        style: "body"
      }
    },
    input: {
      type: "input",
      props: {
        placeholder: "Enter text...",
        type: "text",
        required: false
      }
    },
    card: {
      type: "card",
      props: {
        title: "Card Title",
        elevation: "medium"
      },
      children: []
    },
    container: {
      type: "container",
      props: {
        direction: "column",
        spacing: "medium",
        padding: "medium"
      },
      children: []
    },
    chart: {
      type: "chart",
      props: {
        chartType: "line",
        data: [],
        xAxis: "x",
        yAxis: "y"
      }
    },
    table: {
      type: "table",
      props: {
        columns: [],
        rows: [],
        sortable: true
      }
    }
  };

  // Add component to spec
  const addComponent = (type: string) => {
    const template = componentTemplates[type as keyof typeof componentTemplates];
    const newComponent = { ...template };
    
    setSpec(prev => ({
      ...prev,
      components: [...prev.components, newComponent]
    }));
    
    setSelectedComponent(`component-${spec.components.length}`);
  };

  // Update component
  const updateComponent = (index: number, updates: Partial<A2UIComponent>) => {
    setSpec(prev => ({
      ...prev,
      components: prev.components.map((comp, i) => 
        i === index ? { ...comp, ...updates } : comp
      )
    }));
  };

  // Remove component
  const removeComponent = (index: number) => {
    setSpec(prev => ({
      ...prev,
      components: prev.components.filter((_, i) => i !== index)
    }));
    setSelectedComponent(null);
  };

  // Generate A2UI with CopilotKit
  useCopilotAction({
    name: "generate_a2ui",
    description: "Generate A2UI specification from description",
    parameters: ["description", "context"],
    handler: async ({ description, context }) => {
      setIsGenerating(true);
      try {
        // Call backend to generate A2UI
        const response = await fetch("/api/a2ui/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ description, context })
        });
        
        const result = await response.json();
        
        if (result.spec) {
          setSpec(result.spec);
        }
        
        return result;
      } catch (error) {
        console.error("Generation error:", error);
        return { error: "Failed to generate A2UI" };
      } finally {
        setIsGenerating(false);
      }
    }
  });

  // Export A2UI spec
  const exportSpec = () => {
    const blob = new Blob([JSON.stringify(spec, null, 2)], {
      type: "application/json"
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "a2ui-spec.json";
    a.click();
    URL.revokeObjectURL(url);
  };

  // Import A2UI spec
  const importSpec = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const imported = JSON.parse(e.target?.result as string);
          setSpec(imported);
        } catch (error) {
          console.error("Import error:", error);
          alert("Invalid A2UI specification file");
        }
      };
      reader.readAsText(file);
    }
  };

  // Render component editor
  const renderComponentEditor = (component: A2UIComponent, index: number) => {
    const isSelected = selectedComponent === `component-${index}`;
    
    return (
      <div
        key={index}
        className={`border rounded-lg p-4 cursor-pointer transition-colors ${
          isSelected ? "border-blue-500 bg-blue-50" : "border-gray-200 hover:border-gray-300"
        }`}
        onClick={() => setSelectedComponent(isSelected ? null : `component-${index}`)}
      >
        <div className="flex justify-between items-center mb-2">
          <span className="font-medium text-gray-700">{component.type}</span>
          <button
            onClick={(e) => {
              e.stopPropagation();
              removeComponent(index);
            }}
            className="text-red-500 hover:text-red-700"
          >
            Remove
          </button>
        </div>
        
        {isSelected && (
          <div className="mt-4 space-y-2">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Type
              </label>
              <select
                value={component.type}
                onChange={(e) => updateComponent(index, { type: e.target.value })}
                className="w-full px-2 py-1 border border-gray-300 rounded"
              >
                {Object.keys(componentTemplates).map(type => (
                  <option key={type} value={type}>{type}</option>
                ))}
              </select>
            </div>
            
            {component.props && Object.entries(component.props).map(([key, value]) => (
              <div key={key}>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {key}
                </label>
                <input
                  type="text"
                  value={typeof value === "string" ? value : JSON.stringify(value)}
                  onChange={(e) => {
                    let newValue: any = e.target.value;
                    try {
                      newValue = JSON.parse(e.target.value);
                    } catch {}
                    updateComponent(index, {
                      props: { ...component.props, [key]: newValue }
                    });
                  }}
                  className="w-full px-2 py-1 border border-gray-300 rounded"
                />
              </div>
            ))}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="flex h-screen bg-gray-100">
      {/* Sidebar */}
      <div className="w-80 bg-white shadow-lg p-6 overflow-y-auto">
        <h2 className="text-2xl font-bold mb-6">A2UI Composer</h2>
        
        {/* Component Palette */}
        <div className="mb-6">
          <h3 className="text-lg font-semibold mb-3">Components</h3>
          <div className="grid grid-cols-2 gap-2">
            {Object.keys(componentTemplates).map(type => (
              <button
                key={type}
                onClick={() => addComponent(type)}
                className="px-3 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
              >
                Add {type}
              </button>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="space-y-2">
          <button
            onClick={() => setPreviewMode(!previewMode)}
            className="w-full px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition-colors"
          >
            {previewMode ? "Edit Mode" : "Preview Mode"}
          </button>
          
          <button
            onClick={exportSpec}
            className="w-full px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600 transition-colors"
          >
            Export Spec
          </button>
          
          <label className="block">
            <span className="w-full px-4 py-2 bg-purple-500 text-white rounded hover:bg-purple-600 transition-colors cursor-pointer inline-block text-center">
              Import Spec
            </span>
            <input
              type="file"
              accept=".json"
              onChange={importSpec}
              className="hidden"
            />
          </label>
        </div>

        {/* Metadata */}
        <div className="mt-6">
          <h3 className="text-lg font-semibold mb-3">Metadata</h3>
          <div className="space-y-2">
            <input
              type="text"
              placeholder="Title"
              value={spec.metadata?.title || ""}
              onChange={(e) => setSpec(prev => ({
                ...prev,
                metadata: { ...prev.metadata, title: e.target.value }
              }))}
              className="w-full px-2 py-1 border border-gray-300 rounded"
            />
            <textarea
              placeholder="Description"
              value={spec.metadata?.description || ""}
              onChange={(e) => setSpec(prev => ({
                ...prev,
                metadata: { ...prev.metadata, description: e.target.value }
              }))}
              className="w-full px-2 py-1 border border-gray-300 rounded"
              rows={3}
            />
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex">
        {/* Component List */}
        <div className="w-96 bg-white shadow-lg p-6 overflow-y-auto">
          <h3 className="text-lg font-semibold mb-4">Components</h3>
          <div className="space-y-4">
            {spec.components.map((component, index) => 
              renderComponentEditor(component, index)
            )}
          </div>
        </div>

        {/* Preview */}
        <div className="flex-1 p-6">
          <h3 className="text-lg font-semibold mb-4">
            Preview {isGenerating && "(Generating...)"}
          </h3>
          <div className="bg-white rounded-lg shadow-lg p-6 min-h-[400px]">
            {previewMode ? (
              <div className="a2ui-preview">
                {/* A2UI Renderer would go here */}
                <pre className="text-sm text-gray-600">
                  {JSON.stringify(spec, null, 2)}
                </pre>
              </div>
            ) : (
              <div className="text-gray-500 text-center py-12">
                Click Preview Mode to see the rendered UI
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
